"""Generate weekly report from recent trend insights."""
from datetime import datetime, timezone, timedelta

from sqlalchemy import select, desc

from app.db.session import get_sync_session
from app.models.orm import WeeklyReport, TrendInsight, Topic, TopicDailyMetric, CrossSourceValidation


def _humanize_label(value: str | None) -> str:
    if not value:
        return "Topic"
    return " ".join(value.replace("_", " ").replace("-", " ").split()).title()


def _md_link(title: str | None, url: str | None) -> str:
    """Single markdown link; escape brackets in visible text."""
    if url:
        t = (title or url).replace("[", "\\[").replace("]", "\\]")
        return f"[{t}]({url})"
    return title or ""


def run_weekly_report() -> int | None:
    """Create a weekly report for the past 7 days. Returns report id or None."""
    session = get_sync_session()
    try:
        end = datetime.now(timezone.utc).date()
        start = end - timedelta(days=7)
        insights = (
            session.execute(
                select(TrendInsight, Topic)
                .join(Topic, TrendInsight.topic_id == Topic.id)
                .where(TrendInsight.generated_at >= datetime.combine(start, datetime.min.time()).replace(tzinfo=timezone.utc))
                .where(TrendInsight.generated_at <= datetime.combine(end, datetime.max.time()).replace(tzinfo=timezone.utc))
                .order_by(desc(TrendInsight.generated_at))
                .limit(15)
            )
        ).all()
        if not insights:
            return None
        top_signals = []
        sections = []
        sections.append(f"# Weekly Trend Signal Report — {start} to {end}\n\n")
        sections.append("## Executive summary\n\n")
        sections.append(
            "This week's top signals are derived from Reddit, Hacker News, and arXiv. Below are the leading emerging technology trends.\n\n"
        )
        sections.append("## Top emerging technology signals\n\n")
        for i, (insight, topic) in enumerate(insights[:10], 1):
            score_row = (
                session.execute(
                    select(TopicDailyMetric.signal_score)
                    .where(TopicDailyMetric.topic_id == topic.id)
                    .order_by(desc(TopicDailyMetric.date))
                    .limit(1)
                )
            ).scalars().first()
            cv_row = (
                session.execute(
                    select(CrossSourceValidation.sources_present)
                    .where(CrossSourceValidation.topic_id == topic.id)
                    .order_by(desc(CrossSourceValidation.date))
                    .limit(1)
                )
            ).scalars().first()
            score = f"{score_row:.2f}" if score_row is not None else "N/A"
            sources_str = ", ".join(cv_row) if cv_row else "N/A"
            top_signals.append({"topic_id": topic.id, "insight_id": insight.id, "label": topic.label})
            sections.append(
                f"### {i}. {_humanize_label(topic.label)} — Signal score: {score} | Sources: {sources_str}\n\n"
            )
            sections.append(f"- **What it is:** {insight.summary or 'N/A'}\n")
            sections.append(f"- **Why it matters:** {insight.why_it_matters or 'N/A'}\n")
            sections.append(f"- **Potential impact:** {insight.industry_impact or 'N/A'}\n")
            rep = insight.representative_sources or []
            if rep:
                links = []
                for r in rep[:3]:
                    url = r.get("url")
                    title = r.get("title") or url
                    links.append(_md_link(title, url) if url else (title or ""))
                links = [x for x in links if x]
                if links:
                    sections.append("- **Representative discussions:** " + " · ".join(links) + "\n")
            sections.append("\n")
        sections.append("## Methodology\n\n")
        sections.append(
            "Signals derived from daily ingestion of Reddit (r/technology, r/startups, etc.), Hacker News, and arXiv (cs.AI, cs.LG, etc.). Topics clustered with BERTopic; momentum and cross-source validation used to rank; insights generated by LLM.\n"
        )
        report = WeeklyReport(
            period_start=start,
            period_end=end,
            top_signals=top_signals,
            report_markdown="".join(sections),
            created_at=datetime.now(timezone.utc),
        )
        session.add(report)
        session.commit()
        session.refresh(report)
        return report.id
    except Exception:
        session.rollback()
        return None
    finally:
        session.close()
